#!/usr/bin/env python3
"""
Build a fully static, self-contained browser demo of the WAL logger.

Takes the real logger.html UI verbatim and swaps its server backend for an
in-browser mock (window.fetch override) that replicates wal_logger.py logic
in JavaScript, then seeds it with a real Cabrillo log. The result -
docs/index.html - runs on GitHub Pages (or file://) with no Python server.

Usage:  python build_demo.py [--log demo_log.log]
Re-run whenever logger.html changes to keep the demo in sync.
"""
import os, re, json, argparse, datetime

HERE = os.path.dirname(os.path.abspath(__file__))


# ---------------------------------------------------------------- seed parsing
def qso_points(call):
    c = (call or "").upper().strip()
    if c.endswith("/M") or c.endswith("/MM"):
        return 5
    if c.endswith("/P"):
        return 3
    return 1


def round_for_hour(h):
    return {6: 1, 7: 2, 8: 3}.get(h, 0)


def parse_cabrillo(path):
    """QSO line: freq mode date time MYCALL rst_s sent CALL rst_r rcv."""
    seed, mycall, name, cat = [], "LY5AT/M", "", "M"
    i = 0
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            if line.startswith("CALLSIGN:"):
                mycall = line.split(":", 1)[1].strip() or mycall
            elif line.startswith("NAME:"):
                name = line.split(":", 1)[1].strip()
            elif line.startswith("SOAPBOX: WAL category"):
                cat = line.split()[-1].strip() or cat
            elif line.startswith("QSO:"):
                p = line.split()
                if len(p) < 11:
                    continue
                freq, mode, date, tm, _mc, rst_s, sent, call, rst_r, rcv = p[1:11]
                h = int(tm[:2])
                ts = "%sT%s:%s:00+00:00" % (date, tm[:2], tm[2:4])
                seed.append({
                    "id": i,
                    "ts_utc": ts,
                    "freq_khz": int(freq),
                    "mode": "CW" if mode == "CW" else "SSB",
                    "call": call.upper(),
                    "rst_s": rst_s,
                    "rst_r": rst_r,
                    "sent_wal": sent.upper(),
                    "rcv_wal": rcv.upper(),
                    "points": qso_points(call),
                    "rnd": round_for_hour(h),
                })
                i += 1
    return seed, mycall, name, cat


def read_valid(path):
    valid = set()
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                t = line.strip()
                if t == "DX" or re.match(r"^[A-Z]\d{2}$", t):
                    valid.add(t)
    except OSError:
        pass
    return sorted(valid)


# ---------------------------------------------------------------- browser mock
MOCK_JS = r"""<script>
/* ===== WAL Logger - static browser backend (no server). Auto-generated by build_demo.py ===== */
(function(){
  var VALID = __VALID__;
  var SEED  = __SEED__;
  var CFG0  = __CFG0__;
  var LETTERS="ABCDEFGHIJKLMNOPQRSTUVWXYZ", LAT0=56.5, LON0=20+50/60, STEP=10/60;
  function latlonToWal(lat,lon){ lat=parseFloat(lat); lon=parseFloat(lon);
    if(isNaN(lat)||isNaN(lon)) return null;
    var row=Math.floor(-(lat-LAT0)/STEP), col=Math.floor((lon-LON0)/STEP);
    if(row<0||row>=26||col<0) return null; return LETTERS[row]+String(col).padStart(2,"0"); }
  function pts(call){ var c=(call||"").toUpperCase().trim();
    if(c.endsWith("/M")||c.endsWith("/MM")) return 5; if(c.endsWith("/P")) return 3; return 1; }
  function prefix(call){ var c=(call||"").toUpperCase().trim().split("/")[0];
    var m=c.match(/^([A-Z0-9]*?\d)[A-Z]*$/); return m?m[1]:c; }
  function roundForHour(h){ return ({6:1,7:2,8:3})[h]||0; }
  function J(obj,code){ return Promise.resolve(new Response(JSON.stringify(obj),
    {status:code||200,headers:{"Content-Type":"application/json"}})); }

  var MOCK={
    cfg:Object.assign({mycall:"LY5AT/M",mode:"SSB",freq:"3600",name:"",category:"M",
        round_override:"0",ly_default:"1",sent_wal:"",sent_source:"manual"}, CFG0),
    qsos:SEED.map(function(q){return Object.assign({},q);}),
    nextId:0,
    gps:{lat:null,lon:null,ts:null,hold:null},
    macros:{"1":{label:"CQ",url:null},"2":{label:"Rpt",url:null},"3":{label:"TU",url:null}},
    validSet:new Set(VALID),
    currentRound:function(){ var ov=parseInt(this.cfg.round_override||"0");
      if(ov>=1&&ov<=3) return ov; return roundForHour(new Date().getUTCHours()); },
    stats:function(){ var sq=new Set(),own=new Set(),dx=new Set(),rounds={1:0,2:0,3:0},p=0;
      this.qsos.forEach(function(r){ p+=r.points||0; if(r.sent_wal)own.add(r.sent_wal);
        var rcv=(r.rcv_wal||"").toUpperCase();
        if(rcv==="DX")dx.add(prefix(r.call)); else if(rcv)sq.add(rcv);
        if(rounds[r.rnd]!==undefined)rounds[r.rnd]++; });
      var mult=sq.size+own.size+dx.size;
      return {qsos:this.qsos.length,points:p,squares:sq.size,own_squares:own.size,
        dx_countries:dx.size,mult:mult,score:p*mult,
        worked_squares:Array.from(sq).sort(),own_list:Array.from(own).sort(),rounds:rounds}; },
    setSent:function(w,src){ this.cfg.sent_wal=w; this.cfg.sent_source=src; },
    macroURL:function(n){ return this.macros[n]&&this.macros[n].url; },
    _sorted:function(){ return this.qsos.slice().sort(function(a,b){
      return (a.ts_utc<b.ts_utc?-1:a.ts_utc>b.ts_utc?1:a.id-b.id); }); },
    cabrillo:function(){ var cat=this.cfg.category||"M";
      var stn={M:"MOBILE",P:"PORTABLE",S:"FIXED",K:"FIXED",SWL:"CHECKLOG",KL:"FIXED"}[cat]||"MOBILE";
      var st=this.stats(), mycall=this.cfg.mycall||"LY5AT/M";
      function L(s,n){s=String(s);while(s.length<n)s+=" ";return s;}
      function R(s,n){s=String(s);while(s.length<n)s=" "+s;return s;}
      var out=["START-OF-LOG: 3.0","CONTEST: LY-WAL","CALLSIGN: "+mycall,
        "CATEGORY-OPERATOR: "+(cat==="KL"?"MULTI-OP":"SINGLE-OP"),"CATEGORY-STATION: "+stn,
        "CATEGORY-BAND: 80M","CATEGORY-POWER: LOW","CATEGORY-MODE: MIXED",
        "CLAIMED-SCORE: "+st.score,"NAME: "+(this.cfg.name||""),
        "SOAPBOX: WAL category "+cat,"CREATED-BY: WAL Logger"];
      this._sorted().forEach(function(r){ var d=new Date(r.ts_utc);
        var date=d.getUTCFullYear()+"-"+String(d.getUTCMonth()+1).padStart(2,"0")+"-"+String(d.getUTCDate()).padStart(2,"0");
        var time=String(d.getUTCHours()).padStart(2,"0")+String(d.getUTCMinutes()).padStart(2,"0");
        var md=r.mode==="CW"?"CW":"PH";
        out.push("QSO: "+R(r.freq_khz||3600,5)+" "+L(md,2)+" "+date+" "+time+" "+L(mycall,10)+" "+
          L(r.rst_s,3)+" "+L(r.sent_wal,4)+" "+L((r.call||"").toUpperCase(),10)+" "+L(r.rst_r,3)+" "+L(r.rcv_wal,4)); });
      out.push("END-OF-LOG:"); return out.join("\n")+"\n"; },
    adif:function(){ function f(t,v){v=String(v);return "<"+t+":"+v.length+">"+v;}
      var out=["WAL Contest ADIF export","<ADIF_VER:5>3.1.0","<PROGRAMID:10>WAL Logger","<EOH>"];
      this._sorted().forEach(function(r){ var d=new Date(r.ts_utc);
        var qd=d.getUTCFullYear()+String(d.getUTCMonth()+1).padStart(2,"0")+String(d.getUTCDate()).padStart(2,"0");
        var to=String(d.getUTCHours()).padStart(2,"0")+String(d.getUTCMinutes()).padStart(2,"0")+String(d.getUTCSeconds()).padStart(2,"0");
        out.push([f("CALL",(r.call||"").toUpperCase()),f("QSO_DATE",qd),f("TIME_ON",to),f("BAND","80m"),
          f("FREQ",((r.freq_khz||3600)/1000).toFixed(3)),f("MODE",r.mode==="CW"?"CW":"SSB"),
          f("RST_SENT",r.rst_s),f("RST_RCVD",r.rst_r),f("STX_STRING",r.sent_wal),
          f("SRX_STRING",r.rcv_wal),f("COMMENT","WAL "+r.rcv_wal),"<EOR>"].join(" ")); });
      return out.join("\n")+"\n"; },
    download:function(kind){ var txt=kind==="cabrillo"?this.cabrillo():this.adif();
      var fn=(this.cfg.mycall||"LY5AT").replace(/\//g,"_")+(kind==="cabrillo"?"_WAL.log":"_WAL.adi");
      var b=new Blob([txt],{type:"text/plain;charset=utf-8"}), a=document.createElement("a");
      a.href=URL.createObjectURL(b); a.download=fn; document.body.appendChild(a); a.click();
      setTimeout(function(){URL.revokeObjectURL(a.href); a.remove();},1500); },
    route:function(url,opts){ var self=this; var path=String(url).split("?")[0];
      var data={}; if(opts&&opts.body&&typeof opts.body==="string"){ try{data=JSON.parse(opts.body);}catch(e){} }

      if(path==="/api/state"){ return J({ sent_wal:self.cfg.sent_wal, sent_source:self.cfg.sent_source,
        gps_lat:self.gps.lat, gps_lon:self.gps.lon, gps_ts:self.gps.ts, gps_hold:self.gps.hold,
        stats:self.stats(), mycall:self.cfg.mycall, mode:self.cfg.mode, freq:self.cfg.freq,
        name:self.cfg.name, category:self.cfg.category, round_override:self.cfg.round_override,
        ly_default:self.cfg.ly_default, valid_count:self.validSet.size,
        utc:new Date().toISOString(), current_round:self.currentRound() }); }
      if(path==="/api/valid") return J(VALID);
      if(path==="/api/qsos") return J(self.qsos.slice().sort(function(a,b){return b.id-a.id;}).slice(0,300));
      if(path==="/api/macros"){ var o={}; ["1","2","3"].forEach(function(n){
        o[n]={has:!!self.macros[n].url,label:self.macros[n].label}; }); return J(o); }

      if(path==="/api/dupe"){ var call=(data.call||"").toUpperCase().trim();
        var mode=(data.mode||"SSB").toUpperCase()==="CW"?"CW":"SSB";
        var rnd=self.currentRound(), mysq=self.cfg.sent_wal||"";
        var rows=self.qsos.filter(function(q){return q.call===call&&q.mode===mode&&q.rnd===rnd&&q.sent_wal===mysq;});
        var any=self.qsos.filter(function(q){return q.call===call;});
        return J({count:rows.length, prev_rcv:rows.length?rows[rows.length-1].rcv_wal:"",
          last_rcv:any.length?any[any.length-1].rcv_wal:"", round:rnd, my_square:mysq}); }
      if(path==="/api/qso"){ var call=(data.call||"").toUpperCase().trim(), rcv=(data.rcv_wal||"").toUpperCase().trim();
        if(!call||!rcv) return J({ok:false,error:"call and received WAL required"},400);
        var sent=((data.sent_wal||self.cfg.sent_wal||"")+"").toUpperCase().trim();
        var mode=(data.mode||"SSB").toUpperCase()==="CW"?"CW":"SSB", rd=mode==="CW"?"599":"59";
        var P=pts(call), rnd=self.currentRound(), freq=parseInt(data.freq_khz||3600)||3600;
        self.qsos.push({id:self.nextId++, ts_utc:new Date().toISOString(), freq_khz:freq, mode:mode,
          call:call, rst_s:data.rst_s||rd, rst_r:data.rst_r||rd, sent_wal:sent, rcv_wal:rcv, points:P, rnd:rnd});
        return J({ok:true, points:P, valid_square:(rcv==="DX"||self.validSet.has(rcv)), round:rnd}); }
      if(path==="/api/sent"){ var w=(data.wal||"").trim().toUpperCase(); self.setSent(w,"manual");
        self.gps.hold=latlonToWal(self.gps.lat,self.gps.lon); return J({ok:true,sent_wal:w}); }
      if(path==="/api/gps_auto"){ self.gps.hold=null; var sq=latlonToWal(self.gps.lat,self.gps.lon);
        if(sq)self.setSent(sq,"gps"); else self.cfg.sent_source="gps"; return J({ok:true,square:sq}); }
      if(path==="/api/gps"){ var sq=latlonToWal(data.lat,data.lon);
        self.gps.lat=data.lat; self.gps.lon=data.lon; self.gps.ts=new Date().toISOString();
        if(sq){ if(self.cfg.sent_source==="manual"&&self.cfg.sent_wal){
            if(self.gps.hold==null) self.gps.hold=sq;
            else if(sq!==self.gps.hold){ self.setSent(sq,"gps"); self.gps.hold=null; } }
          else self.setSent(sq,"gps"); }
        return J({ok:true,square:sq}); }
      if(path==="/api/mycall"){ self.cfg.mycall=(data.mycall||"").trim().toUpperCase(); return J({ok:true}); }
      if(path==="/api/band"){ self.cfg.mode=(data.mode||"SSB").toUpperCase()==="CW"?"CW":"SSB";
        self.cfg.freq=String(parseInt(data.freq||3600)||3600); return J({ok:true}); }
      if(path==="/api/cfgset"){ var k=String(data.key), v=(data.value||"").trim();
        if(["mycall","name","category","round_override","ly_default"].indexOf(k)>=0)
          self.cfg[k]=(k==="mycall"?v.toUpperCase():v); return J({ok:true}); }
      if(path==="/api/macrolabel"){ var n=String(data.n); if(self.macros[n])self.macros[n].label=(data.label||"").trim(); return J({ok:true}); }
      if(path==="/api/qso/delete"){ self.qsos=self.qsos.filter(function(q){return q.id!==data.id;}); return J({ok:true}); }
      if(path==="/api/qso/update"){ var row=null; self.qsos.forEach(function(q){if(q.id===data.id)row=q;});
        if(!row) return J({ok:false,error:"not found"},404);
        row.call=(data.call||row.call).trim().toUpperCase();
        row.rcv_wal=(data.rcv_wal||row.rcv_wal).trim().toUpperCase();
        row.sent_wal=((data.sent_wal!=null?data.sent_wal:row.sent_wal)+"").trim().toUpperCase();
        row.mode=(data.mode||row.mode).toUpperCase()==="CW"?"CW":"SSB";
        row.rst_s=data.rst_s||row.rst_s; row.rst_r=data.rst_r||row.rst_r;
        row.freq_khz=parseInt(data.freq_khz||row.freq_khz||3600)||3600; row.points=pts(row.call);
        return J({ok:true,points:row.points}); }
      if(path==="/api/backup") return J({ok:true,backup:"(demo - neirasoma)"});
      if(path==="/api/wipe"){ var n=self.qsos.length; self.qsos=[]; return J({ok:true,cleared:n,backup:"(demo)"}); }
      if(path.indexOf("/api/macro/")===0){ var n=path.substring(11);
        if(self.macros[n]){ try{ if(opts&&opts.body) self.macros[n].url=URL.createObjectURL(opts.body); }catch(e){} }
        return J({ok:true}); }
      return J({ok:false,error:"unknown "+path},404); }
  };
  MOCK.qsos.forEach(function(q){ if(q.id>=MOCK.nextId) MOCK.nextId=q.id+1; });
  if(!MOCK.cfg.sent_wal && MOCK.qsos.length) MOCK.cfg.sent_wal=MOCK.qsos[MOCK.qsos.length-1].sent_wal||"";
  window.MOCK=MOCK;
  window.fetch=function(url,opts){ return MOCK.route(String(url),opts||{}); };

  function wire(){
    var c=document.getElementById("exCab"), a=document.getElementById("exAdif"), r=document.getElementById("demoReset");
    if(c)c.onclick=function(){MOCK.download("cabrillo");};
    if(a)a.onclick=function(){MOCK.download("adif");};
    if(r)r.onclick=function(){location.reload();};
  }
  if(document.readyState==="loading") document.addEventListener("DOMContentLoaded",wire); else wire();
})();
</script>
"""


BANNER = """
<div id="demoBar" style="background:#13233a;border-bottom:1px solid #26344a;color:#cfe0f5;
  font:13px/1.4 system-ui,Segoe UI,Roboto,sans-serif;padding:8px 14px;display:flex;gap:10px;
  align-items:center;flex-wrap:wrap">
  <span style="background:#37d67a;color:#04130a;font-weight:800;border-radius:6px;padding:2px 8px;letter-spacing:.5px">DEMO</span>
  <span>Užkrautas tikras <b>LY5AT/M</b> WAL 2026 logas (110 QSO). Loginki ryšius, tikrink dublius (nustatyk
  <b>Turą</b> 1-3 ir įvesk jau darytą stotį), eksportuok Cabrillo/ADIF - viskas veikia naršyklėje, nieko diegti nereikia.</span>
  <button id="demoReset" style="margin-left:auto;background:#0c1220;border:1px solid #26344a;color:#cfe0f5;
    border-radius:8px;padding:6px 12px;cursor:pointer">↻ Iš naujo</button>
  <a href="https://github.com/LY5AT/wal-logger" style="color:#4aa8ff;text-decoration:none;font-weight:700">GitHub ⌁</a>
</div>
"""


def build(log_path, valid_path, src_html, out_html):
    seed, mycall, name, cat = parse_cabrillo(log_path)
    valid = read_valid(valid_path)
    with open(src_html, "r", encoding="utf-8") as f:
        html = f.read()

    cfg0 = {"mycall": mycall, "name": name, "category": cat}
    mock = (MOCK_JS
            .replace("__VALID__", json.dumps(valid))
            .replace("__SEED__", json.dumps(seed, separators=(",", ":")))
            .replace("__CFG0__", json.dumps(cfg0)))

    reps = [
        # title
        ("<title>WAL Contest Logger</title>",
         "<title>WAL Contest Logger - gyvas demo</title>"),
        # demo banner right after <body>
        ("<body>", "<body>" + BANNER),
        # export anchors -> buttons (downloads built client-side)
        ('<a href="/export/cabrillo">⬇ Cabrillo</a><a href="/export/adif">⬇ ADIF</a>',
         '<button id="exCab">⬇ Cabrillo</button><button id="exAdif">⬇ ADIF</button>'),
        # voice keyer plays from a client-side object URL instead of a server path
        ('  curAudio=new Audio("/macro/"+n+"?"+Date.now());',
         '  var _mu=MOCK.macroURL(n); if(!_mu){$("#hint").innerHTML=\'<span class="bad">F\'+n+\': nėra įrašo</span>\';return;} curAudio=new Audio(_mu);'),
        # no "leave page?" prompt in a demo
        ('window.addEventListener("beforeunload",e=>{ if(totalQsos>0){ e.preventDefault(); e.returnValue=""; } });',
         '/* demo: no beforeunload prompt */'),
        # inject the mock backend immediately before the UI script
        ("<script>\nconst $ = s => document.querySelector(s);",
         mock + "\n<script>\nconst $ = s => document.querySelector(s);"),
    ]
    for old, new in reps:
        if old not in html:
            raise SystemExit("PATTERN NOT FOUND (logger.html changed?):\n  " + old[:80])
        html = html.replace(old, new, 1)

    with open(out_html, "w", encoding="utf-8") as f:
        f.write(html)

    st_pts = sum(q["points"] for q in seed)
    print("Built %s" % out_html)
    print("  seed: %d QSO  (%s, kat. %s)" % (len(seed), mycall, cat))
    print("  valid squares: %d (+DX)" % (len(valid) - (1 if "DX" in valid else 0)))
    print("  raw points: %d" % st_pts)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--log", default=os.path.join(HERE, "demo_log.log"))
    ap.add_argument("--sec", default=os.path.join(HERE, "LYWAL.sec"))
    ap.add_argument("--src", default=os.path.join(HERE, "logger.html"))
    ap.add_argument("--out", default=os.path.join(HERE, "docs", "index.html"))
    a = ap.parse_args()
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    build(a.log, a.sec, a.src, a.out)
